version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      # - "3000:3000"
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - app-network
    command: npm run dev -- --host # vite 추가

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/db
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules // 익명 볼륨(컨테이너 전용)
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
